### ISSUE TITLE
Use Git LFS for large PDFs

### ISSUE THREAD

**Issue by luxas** [cloud-native-nordics/meetups#11]
Otherwise cloning will be super slow and inefficient in the end
cc @kaspernissen would this be ok?

**Comment by kaspernissen** [comment]
Does anybody have experience migrating an existing repo? After reading a little bit about it, It seems that you have to delete and re-add all the files after git lfs is configured.

**Comment by luxas** [comment]
I have experience with that in Gitlab. It's scary; because it's rewriting every commit and requires a `git push -f` but hence I think we should try to do it sooner rather than later.

**Comment by Steiniche** [comment]
I have done it in bitbucket and it is the same experience as @luxas describes with gitlab.
Sooner than later is recommended!

**Comment by luxas** [comment]
I verified and it's working. If you give green light after checking my repo, I'll then go ahead and force-push the master branch of this repo.

**Comment by kaspernissen** [comment]
Looks good to me @luxas. It's only *.pdf, right? Maybe we should consider adding video files as well. We currently have an mp4 file in the aarhus group.

**Comment by luxas** [comment]
This is now done, see e.g. https://github.com/cloud-native-nordics/meetups/blob/master/aarhus/2017/cloud-native-aarhus-1/lunar-way-cloud-native-aarhus-may-2017.pdf or https://github.com/cloud-native-nordics/meetups/blob/master/.gitattributes
I also added *.mp4 to the list. From now on I'm gonna add branch protection to the master branch so folks can't force push it like I now did :smile:
