### ISSUE TITLE
Add Turku to the list of cities in the talk proposal form for Finland

### ISSUE THREAD

**Issue by lentzi90** [cloud-native-nordics/meetups#111]
Can we add Turku to the list of cities instead of having to select "other" and type the name in [this form](https://docs.google.com/forms/d/e/1FAIpQLSfmOW-hR3So_tblhQefjbG7R7akWnasfJx0SpDXsNeADaSIpg/viewform)? :slightly_smiling_face:

**Comment by luxas** [comment]
Yes :smile:! Fixed now, sorry that I didn't get to it earlier.
