### ISSUE TITLE
Collaborate on slide deck templates?

### ISSUE THREAD

**Issue by luxas** [cloud-native-nordics/meetups#20]
Should we share templates for our meetup slide decks?

**Comment by kaspernissen** [comment]
Yes, that would be cool. 

We currently use a google slide template that aligns with some of the official CNCF slide decks with some modifications. What are you using?

**Comment by luxas** [comment]
Also a deck that is partly using the official CNCF template: https://docs.google.com/presentation/d/1iT3rmWQ-Z1IDv3W5eeKzP8m4E7MBf5dHBR1-Ca6U4Ss/edit#slide=id.g4c775a0cfb_0_0

**Comment by Steiniche** [comment]
You can see ours here: 
https://docs.google.com/presentation/d/1lKpyHM76U3k1oVJlVEnj2mwZmdtJmfQ2uxAnamMXCyA/edit?usp=sharing

**Comment by luxas** [comment]
Issue moved to https://github.com/cloud-native-nordics/artwork/issues/5
