### ISSUE TITLE
Declaratively specify content using a YAML file

### ISSUE THREAD

**Issue by luxas** [cloud-native-nordics/meetups#3]
Store a YAML file for every location that specifies everything needed, and generate docs based on that

**Comment by kaspernissen** [comment]
Sounds interesting. What kind of information do you think should be in the docs?

**Comment by luxas** [comment]
I haven't had time to look at a spec yet, but something structured out of the bullet points in https://github.com/cloud-native-finland/meetups/tree/master/helsinki

You can get inspiration from here https://github.com/kubernetes/community/tree/master/generator :smile:
