### ISSUE TITLE
Add the Swedish meetups

### ISSUE THREAD

**Issue by luxas** [cloud-native-nordics/meetups#32]
@dzolotusky can you help here? Please cc the other organizers here so we can add them to the gh org.
Let's collaborate with e.g. these meetups
 - https://www.meetup.com/sthlm-k8s/
 - https://www.meetup.com/Cloud-Native-Computing-Stockholm/
 - https://www.meetup.com/Cloud-Native-Northern-Sweden/

I couldn't find Robert Winter who organizes the Northern Sweden meetup but I'll try to get in touch with him via email

**Comment by iljoo** [comment]
Hi there! I am one of the organizers from Sweden. Please add me.

**Comment by kaspernissen** [comment]
Welcome @iljoo ! Did you also join our Slack Community? https://www.cloudnativenordics.com, then we can add you to the organizers channel as well.

**Comment by winterrobert** [comment]
Hey guys, great initiative I've joined the Slack channel.

**Comment by Steiniche** [comment]
Hi @winterrobert and welcome!
What is your slack alias? Then we can add you to the organizers channel.
