### ISSUE TITLE
Makefile outputs a linux binary

### ISSUE THREAD

**Issue by kaspernissen** [cloud-native-nordics/meetups#40]
The current implementation of the `Makefile` outputs a linux binary to the host machine, which the rest of the `make` targets rely on. 

This binary cannot be executed on e.g. a Mac. 

Maybe we should wrap the binary in a container instead, making it portable between platforms?

**Comment by jnummelin** [comment]
I've lately using [gox](https://github.com/mitchellh/gox) to build bins for multiple archs easily. An example: https://github.com/jnummelin/s3-url-signer/blob/master/build.sh#L9

**Comment by kaspernissen** [comment]
Haven't used gox before, but it looks quite simple. You would have to compile multiple binaries and switch in the Makefile based on the current arch, right? 

Another solution could be to wrap the binary in a docker container with something like this:
```
FROM golang:1.11
WORKDIR /generator

COPY generator .
COPY meetups.yaml .
RUN go build -mod vendor -o bin/generator .

ENTRYPOINT ["/generator/bin/generator"]
```

and then replace the make target `bin-generator` with
```
generator/bin/generator bin-generator:
	docker build -t generator .
```

and use a docker run the other targets:
```
dry-run: generator/bin/generator
	docker run --rm -v $(shell pwd):/app generator:latest  --config /app/meetups.yaml --dry-run=true
```

That should ensure portability, and no logic in terms of switching between archs.

**Comment by luxas** [comment]
The easiest way to fix this is to set GOARCH/GOOS to the host's `go env GOARCH/GOOS`, this is like a two-line fix
