### ISSUE TITLE
Add meetup guidelines

### ISSUE THREAD

**Issue by luxas** [cloud-native-nordics/meetups#6]
like https://github.com/cloud-native-finland/meetups/blob/master/SPEAKER_GUIDE.md, but more about best practices how to run a meetup

**Comment by kaspernissen** [comment]
Is it ok with you, @luxas, that we use your guidelines as the initial guidelines here? Then we can iterate on them here? I can just recreate them here with the small changes.

**Comment by luxas** [comment]
Yes, I will do that.
