### ISSUE TITLE
Suggestion: Create a new Meetup Group Starter Guide

### ISSUE THREAD

**Issue by AllanHoejgaardJensen** [cloud-native-nordics/meetups#71]
When creating a new group, there are a number of things that are explained in the repos already, other things may not be as clear to new people joining the nordics with the aim of being a good citizen. 

There is a clear definition of how to use the artwork stuff, maybe some clarity of whether it is expected to create a PR for the slide-background in order to have your background in that repo as well (once more people did that it might become obvious and it would be easy to switch backgrounds on slides if you wanted to change that according to the city - if that is thought of as being useful)

Other things may not be as clear e.g. that it is a good idea to create a private slack channel for the city e.g. "cloudnativeaarhus" or "cloudnativeaalborg", and create a private channel for each meetup involving e.g. external speakers, sponsors etc.   e.g. "cloudnativeaarhus17" or "cloudnativeaalborg1", where the number is the meetup number. These are kept private in order to reduce the noise in the public part of slack.

Another valuable information would be to link to the page informing on the terms to be part of cncf meetup program.

Yet another valuable information could be how to start using the tools in this repo, what to add and where and what gets generated from the meetup API etc. - the thing that @luxas talked about in the hangout.

Maybe the #29 is somehow linked to portions of this?

I can keep adding things as I experience them, however if people think it would be useful to create a "Starting-your-own-town-CNCF-Meetup-group.md" file for that purpose, then that might be the best place to add that information.

**Comment by kaspernissen** [comment]
I think it would be a good idea with a getting started guide. Maybe `Starting-you-own-CNCF-Meetup-group.md`. 

Would you mind taking the first stab at this, @AllanHoejgaardJensen? Now that's everything is fresh in mind. Purhaps, @Solisol can provide some of the same learnings .

**Comment by AllanHoejgaardJensen** [comment]
Sure I will start that, I am taking notes and have been taking notes from the start. I will continue to do so until we have conducted the first meetup and then I will create the Starting-you-own-CNCF-Meetup-group.md at that time.

**Comment by Steiniche** [comment]
Brilliant @AllanHoejgaardJensen - looking forward to the PR!

**Comment by luxas** [comment]
This is now done, and further simplified in #92 :smile:
